/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.ccdak.practice.basicKafka.messaging;
@org.apache.avro.specific.AvroGenerated
public enum action implements org.apache.avro.generic.GenericEnumSymbol<action> {
  LOGIN, LOGOUT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"action\",\"namespace\":\"org.ccdak.practice.basicKafka.messaging\",\"symbols\":[\"LOGIN\",\"LOGOUT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
