// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccdak.proto

package org.ccdak.practice.basicKafka.messaging;

public final class ExamProto {
  private ExamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Exam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string purchase = 1;</code>
     * @return Whether the purchase field is set.
     */
    boolean hasPurchase();
    /**
     * <code>string purchase = 1;</code>
     * @return The purchase.
     */
    java.lang.String getPurchase();
    /**
     * <code>string purchase = 1;</code>
     * @return The bytes for purchase.
     */
    com.google.protobuf.ByteString
        getPurchaseBytes();

    /**
     * <code>string return = 2;</code>
     * @return Whether the return field is set.
     */
    boolean hasReturn();
    /**
     * <code>string return = 2;</code>
     * @return The return.
     */
    java.lang.String getReturn();
    /**
     * <code>string return = 2;</code>
     * @return The bytes for return.
     */
    com.google.protobuf.ByteString
        getReturnBytes();

    org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.UserActionCase getUserActionCase();
  }
  /**
   * Protobuf type {@code Exam}
   */
  public static final class Exam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Exam)
      ExamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exam.newBuilder() to construct.
    private Exam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exam() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Exam();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ccdak.practice.basicKafka.messaging.ExamProto.internal_static_Exam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ccdak.practice.basicKafka.messaging.ExamProto.internal_static_Exam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.class, org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.Builder.class);
    }

    private int userActionCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object userAction_;
    public enum UserActionCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PURCHASE(1),
      RETURN(2),
      USERACTION_NOT_SET(0);
      private final int value;
      private UserActionCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserActionCase valueOf(int value) {
        return forNumber(value);
      }

      public static UserActionCase forNumber(int value) {
        switch (value) {
          case 1: return PURCHASE;
          case 2: return RETURN;
          case 0: return USERACTION_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public UserActionCase
    getUserActionCase() {
      return UserActionCase.forNumber(
          userActionCase_);
    }

    public static final int PURCHASE_FIELD_NUMBER = 1;
    /**
     * <code>string purchase = 1;</code>
     * @return Whether the purchase field is set.
     */
    public boolean hasPurchase() {
      return userActionCase_ == 1;
    }
    /**
     * <code>string purchase = 1;</code>
     * @return The purchase.
     */
    public java.lang.String getPurchase() {
      java.lang.Object ref = "";
      if (userActionCase_ == 1) {
        ref = userAction_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (userActionCase_ == 1) {
          userAction_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string purchase = 1;</code>
     * @return The bytes for purchase.
     */
    public com.google.protobuf.ByteString
        getPurchaseBytes() {
      java.lang.Object ref = "";
      if (userActionCase_ == 1) {
        ref = userAction_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (userActionCase_ == 1) {
          userAction_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURN_FIELD_NUMBER = 2;
    /**
     * <code>string return = 2;</code>
     * @return Whether the return field is set.
     */
    public boolean hasReturn() {
      return userActionCase_ == 2;
    }
    /**
     * <code>string return = 2;</code>
     * @return The return.
     */
    public java.lang.String getReturn() {
      java.lang.Object ref = "";
      if (userActionCase_ == 2) {
        ref = userAction_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (userActionCase_ == 2) {
          userAction_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string return = 2;</code>
     * @return The bytes for return.
     */
    public com.google.protobuf.ByteString
        getReturnBytes() {
      java.lang.Object ref = "";
      if (userActionCase_ == 2) {
        ref = userAction_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (userActionCase_ == 2) {
          userAction_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userActionCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userAction_);
      }
      if (userActionCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userAction_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userActionCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userAction_);
      }
      if (userActionCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userAction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ccdak.practice.basicKafka.messaging.ExamProto.Exam)) {
        return super.equals(obj);
      }
      org.ccdak.practice.basicKafka.messaging.ExamProto.Exam other = (org.ccdak.practice.basicKafka.messaging.ExamProto.Exam) obj;

      if (!getUserActionCase().equals(other.getUserActionCase())) return false;
      switch (userActionCase_) {
        case 1:
          if (!getPurchase()
              .equals(other.getPurchase())) return false;
          break;
        case 2:
          if (!getReturn()
              .equals(other.getReturn())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (userActionCase_) {
        case 1:
          hash = (37 * hash) + PURCHASE_FIELD_NUMBER;
          hash = (53 * hash) + getPurchase().hashCode();
          break;
        case 2:
          hash = (37 * hash) + RETURN_FIELD_NUMBER;
          hash = (53 * hash) + getReturn().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ccdak.practice.basicKafka.messaging.ExamProto.Exam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Exam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Exam)
        org.ccdak.practice.basicKafka.messaging.ExamProto.ExamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ccdak.practice.basicKafka.messaging.ExamProto.internal_static_Exam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ccdak.practice.basicKafka.messaging.ExamProto.internal_static_Exam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.class, org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.Builder.class);
      }

      // Construct using org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userActionCase_ = 0;
        userAction_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ccdak.practice.basicKafka.messaging.ExamProto.internal_static_Exam_descriptor;
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.ExamProto.Exam getDefaultInstanceForType() {
        return org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.getDefaultInstance();
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.ExamProto.Exam build() {
        org.ccdak.practice.basicKafka.messaging.ExamProto.Exam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.ExamProto.Exam buildPartial() {
        org.ccdak.practice.basicKafka.messaging.ExamProto.Exam result = new org.ccdak.practice.basicKafka.messaging.ExamProto.Exam(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(org.ccdak.practice.basicKafka.messaging.ExamProto.Exam result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(org.ccdak.practice.basicKafka.messaging.ExamProto.Exam result) {
        result.userActionCase_ = userActionCase_;
        result.userAction_ = this.userAction_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ccdak.practice.basicKafka.messaging.ExamProto.Exam) {
          return mergeFrom((org.ccdak.practice.basicKafka.messaging.ExamProto.Exam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ccdak.practice.basicKafka.messaging.ExamProto.Exam other) {
        if (other == org.ccdak.practice.basicKafka.messaging.ExamProto.Exam.getDefaultInstance()) return this;
        switch (other.getUserActionCase()) {
          case PURCHASE: {
            userActionCase_ = 1;
            userAction_ = other.userAction_;
            onChanged();
            break;
          }
          case RETURN: {
            userActionCase_ = 2;
            userAction_ = other.userAction_;
            onChanged();
            break;
          }
          case USERACTION_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                userActionCase_ = 1;
                userAction_ = s;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                userActionCase_ = 2;
                userAction_ = s;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int userActionCase_ = 0;
      private java.lang.Object userAction_;
      public UserActionCase
          getUserActionCase() {
        return UserActionCase.forNumber(
            userActionCase_);
      }

      public Builder clearUserAction() {
        userActionCase_ = 0;
        userAction_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>string purchase = 1;</code>
       * @return Whether the purchase field is set.
       */
      @java.lang.Override
      public boolean hasPurchase() {
        return userActionCase_ == 1;
      }
      /**
       * <code>string purchase = 1;</code>
       * @return The purchase.
       */
      @java.lang.Override
      public java.lang.String getPurchase() {
        java.lang.Object ref = "";
        if (userActionCase_ == 1) {
          ref = userAction_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (userActionCase_ == 1) {
            userAction_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string purchase = 1;</code>
       * @return The bytes for purchase.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPurchaseBytes() {
        java.lang.Object ref = "";
        if (userActionCase_ == 1) {
          ref = userAction_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (userActionCase_ == 1) {
            userAction_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string purchase = 1;</code>
       * @param value The purchase to set.
       * @return This builder for chaining.
       */
      public Builder setPurchase(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userActionCase_ = 1;
        userAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string purchase = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPurchase() {
        if (userActionCase_ == 1) {
          userActionCase_ = 0;
          userAction_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string purchase = 1;</code>
       * @param value The bytes for purchase to set.
       * @return This builder for chaining.
       */
      public Builder setPurchaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userActionCase_ = 1;
        userAction_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string return = 2;</code>
       * @return Whether the return field is set.
       */
      @java.lang.Override
      public boolean hasReturn() {
        return userActionCase_ == 2;
      }
      /**
       * <code>string return = 2;</code>
       * @return The return.
       */
      @java.lang.Override
      public java.lang.String getReturn() {
        java.lang.Object ref = "";
        if (userActionCase_ == 2) {
          ref = userAction_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (userActionCase_ == 2) {
            userAction_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string return = 2;</code>
       * @return The bytes for return.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReturnBytes() {
        java.lang.Object ref = "";
        if (userActionCase_ == 2) {
          ref = userAction_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (userActionCase_ == 2) {
            userAction_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string return = 2;</code>
       * @param value The return to set.
       * @return This builder for chaining.
       */
      public Builder setReturn(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userActionCase_ = 2;
        userAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string return = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReturn() {
        if (userActionCase_ == 2) {
          userActionCase_ = 0;
          userAction_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string return = 2;</code>
       * @param value The bytes for return to set.
       * @return This builder for chaining.
       */
      public Builder setReturnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userActionCase_ = 2;
        userAction_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Exam)
    }

    // @@protoc_insertion_point(class_scope:Exam)
    private static final org.ccdak.practice.basicKafka.messaging.ExamProto.Exam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ccdak.practice.basicKafka.messaging.ExamProto.Exam();
    }

    public static org.ccdak.practice.basicKafka.messaging.ExamProto.Exam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Exam>
        PARSER = new com.google.protobuf.AbstractParser<Exam>() {
      @java.lang.Override
      public Exam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Exam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ccdak.practice.basicKafka.messaging.ExamProto.Exam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013ccdak.proto\";\n\004Exam\022\022\n\010purchase\030\001 \001(\tH" +
      "\000\022\020\n\006return\030\002 \001(\tH\000B\r\n\013user_actionB4\n\'or" +
      "g.ccdak.practice.basicKafka.messagingB\tE" +
      "xamProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Exam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Exam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exam_descriptor,
        new java.lang.String[] { "Purchase", "Return", "UserAction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
