/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.ccdak.practice.basicKafka.messaging;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Exam extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4457033291421637857L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Exam\",\"namespace\":\"org.ccdak.practice.basicKafka.messaging\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"options\",\"type\":{\"type\":\"map\",\"values\":\"double\"}},{\"name\":\"category\",\"type\":{\"type\":\"enum\",\"name\":\"action\",\"symbols\":[\"LOGIN\",\"LOGOUT\"]},\"default\":\"LOGIN\"},{\"name\":\"tags\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Complex Type: Array of strings\",\"default\":[]},{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"doc\":\"Complex Type: Map (Keys in Avro maps are always strings)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Exam> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Exam> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Exam> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Exam> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Exam> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Exam to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Exam from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Exam instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Exam fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence message;
  private java.lang.CharSequence type;
  private java.util.Map<java.lang.CharSequence,java.lang.Double> options;
  private org.ccdak.practice.basicKafka.messaging.action category;
  /** Complex Type: Array of strings */
  private java.util.List<java.lang.CharSequence> tags;
  /** Complex Type: Map (Keys in Avro maps are always strings) */
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Exam() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param type The new value for type
   * @param options The new value for options
   * @param category The new value for category
   * @param tags Complex Type: Array of strings
   * @param metadata Complex Type: Map (Keys in Avro maps are always strings)
   */
  public Exam(java.lang.CharSequence message, java.lang.CharSequence type, java.util.Map<java.lang.CharSequence,java.lang.Double> options, org.ccdak.practice.basicKafka.messaging.action category, java.util.List<java.lang.CharSequence> tags, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata) {
    this.message = message;
    this.type = type;
    this.options = options;
    this.category = category;
    this.tags = tags;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return type;
    case 2: return options;
    case 3: return category;
    case 4: return tags;
    case 5: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: options = (java.util.Map<java.lang.CharSequence,java.lang.Double>)value$; break;
    case 3: category = (org.ccdak.practice.basicKafka.messaging.action)value$; break;
    case 4: tags = (java.util.List<java.lang.CharSequence>)value$; break;
    case 5: metadata = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'options' field.
   * @return The value of the 'options' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Double> getOptions() {
    return options;
  }


  /**
   * Sets the value of the 'options' field.
   * @param value the value to set.
   */
  public void setOptions(java.util.Map<java.lang.CharSequence,java.lang.Double> value) {
    this.options = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public org.ccdak.practice.basicKafka.messaging.action getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(org.ccdak.practice.basicKafka.messaging.action value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'tags' field.
   * @return Complex Type: Array of strings
   */
  public java.util.List<java.lang.CharSequence> getTags() {
    return tags;
  }


  /**
   * Sets the value of the 'tags' field.
   * Complex Type: Array of strings
   * @param value the value to set.
   */
  public void setTags(java.util.List<java.lang.CharSequence> value) {
    this.tags = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return Complex Type: Map (Keys in Avro maps are always strings)
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * Complex Type: Map (Keys in Avro maps are always strings)
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.metadata = value;
  }

  /**
   * Creates a new Exam RecordBuilder.
   * @return A new Exam RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Exam.Builder newBuilder() {
    return new org.ccdak.practice.basicKafka.messaging.Exam.Builder();
  }

  /**
   * Creates a new Exam RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Exam RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Exam.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.Exam.Builder other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.Exam.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.Exam.Builder(other);
    }
  }

  /**
   * Creates a new Exam RecordBuilder by copying an existing Exam instance.
   * @param other The existing instance to copy.
   * @return A new Exam RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Exam.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.Exam other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.Exam.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.Exam.Builder(other);
    }
  }

  /**
   * RecordBuilder for Exam instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Exam>
    implements org.apache.avro.data.RecordBuilder<Exam> {

    private java.lang.CharSequence message;
    private java.lang.CharSequence type;
    private java.util.Map<java.lang.CharSequence,java.lang.Double> options;
    private org.ccdak.practice.basicKafka.messaging.action category;
    /** Complex Type: Array of strings */
    private java.util.List<java.lang.CharSequence> tags;
    /** Complex Type: Map (Keys in Avro maps are always strings) */
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.Exam.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.options)) {
        this.options = data().deepCopy(fields()[2].schema(), other.options);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.category)) {
        this.category = data().deepCopy(fields()[3].schema(), other.category);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.tags)) {
        this.tags = data().deepCopy(fields()[4].schema(), other.tags);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Exam instance
     * @param other The existing instance to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.Exam other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.options)) {
        this.options = data().deepCopy(fields()[2].schema(), other.options);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.category)) {
        this.category = data().deepCopy(fields()[3].schema(), other.category);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tags)) {
        this.tags = data().deepCopy(fields()[4].schema(), other.tags);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.metadata)) {
        this.metadata = data().deepCopy(fields()[5].schema(), other.metadata);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'options' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Double> getOptions() {
      return options;
    }


    /**
      * Sets the value of the 'options' field.
      * @param value The value of 'options'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setOptions(java.util.Map<java.lang.CharSequence,java.lang.Double> value) {
      validate(fields()[2], value);
      this.options = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'options' field has been set.
      * @return True if the 'options' field has been set, false otherwise.
      */
    public boolean hasOptions() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'options' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearOptions() {
      options = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public org.ccdak.practice.basicKafka.messaging.action getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setCategory(org.ccdak.practice.basicKafka.messaging.action value) {
      validate(fields()[3], value);
      this.category = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearCategory() {
      category = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'tags' field.
      * Complex Type: Array of strings
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getTags() {
      return tags;
    }


    /**
      * Sets the value of the 'tags' field.
      * Complex Type: Array of strings
      * @param value The value of 'tags'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setTags(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.tags = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'tags' field has been set.
      * Complex Type: Array of strings
      * @return True if the 'tags' field has been set, false otherwise.
      */
    public boolean hasTags() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'tags' field.
      * Complex Type: Array of strings
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearTags() {
      tags = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Complex Type: Map (Keys in Avro maps are always strings)
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * Complex Type: Map (Keys in Avro maps are always strings)
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder setMetadata(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.metadata = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Complex Type: Map (Keys in Avro maps are always strings)
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Complex Type: Map (Keys in Avro maps are always strings)
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Exam.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Exam build() {
      try {
        Exam record = new Exam();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.options = fieldSetFlags()[2] ? this.options : (java.util.Map<java.lang.CharSequence,java.lang.Double>) defaultValue(fields()[2]);
        record.category = fieldSetFlags()[3] ? this.category : (org.ccdak.practice.basicKafka.messaging.action) defaultValue(fields()[3]);
        record.tags = fieldSetFlags()[4] ? this.tags : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        record.metadata = fieldSetFlags()[5] ? this.metadata : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Exam>
    WRITER$ = (org.apache.avro.io.DatumWriter<Exam>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Exam>
    READER$ = (org.apache.avro.io.DatumReader<Exam>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.message);

    out.writeString(this.type);

    long size0 = this.options.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.Double> e0: this.options.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.Double v0 = e0.getValue();
      out.writeDouble(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeEnum(this.category.ordinal());

    long size1 = this.tags.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (java.lang.CharSequence e1: this.tags) {
      actualSize1++;
      out.startItem();
      out.writeString(e1);
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

    long size2 = this.metadata.size();
    out.writeMapStart();
    out.setItemCount(size2);
    long actualSize2 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e2: this.metadata.entrySet()) {
      actualSize2++;
      out.startItem();
      out.writeString(e2.getKey());
      java.lang.CharSequence v2 = e2.getValue();
      out.writeString(v2);
    }
    out.writeMapEnd();
    if (actualSize2 != size2)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size2 + ", but element count was " + actualSize2 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.Double> m0 = this.options; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.Double>((int)size0);
        this.options = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.Double v0 = null;
          v0 = in.readDouble();
          m0.put(k0, v0);
        }
      }

      this.category = org.ccdak.practice.basicKafka.messaging.action.values()[in.readEnum()];

      long size1 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a1 = this.tags;
      if (a1 == null) {
        a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("tags").schema());
        this.tags = a1;
      } else a1.clear();
      SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
          e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
          a1.add(e1);
        }
      }

      long size2 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m2 = this.metadata; // Need fresh name due to limitation of macro system
      if (m2 == null) {
        m2 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size2);
        this.metadata = m2;
      } else m2.clear();
      for ( ; 0 < size2; size2 = in.mapNext()) {
        for ( ; size2 != 0; size2--) {
          java.lang.CharSequence k2 = null;
          k2 = in.readString(k2 instanceof Utf8 ? (Utf8)k2 : null);
          java.lang.CharSequence v2 = null;
          v2 = in.readString(v2 instanceof Utf8 ? (Utf8)v2 : null);
          m2.put(k2, v2);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 1:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 2:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.Double> m0 = this.options; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.Double>((int)size0);
            this.options = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.Double v0 = null;
              v0 = in.readDouble();
              m0.put(k0, v0);
            }
          }
          break;

        case 3:
          this.category = org.ccdak.practice.basicKafka.messaging.action.values()[in.readEnum()];
          break;

        case 4:
          long size1 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a1 = this.tags;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("tags").schema());
            this.tags = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
              a1.add(e1);
            }
          }
          break;

        case 5:
          long size2 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m2 = this.metadata; // Need fresh name due to limitation of macro system
          if (m2 == null) {
            m2 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size2);
            this.metadata = m2;
          } else m2.clear();
          for ( ; 0 < size2; size2 = in.mapNext()) {
            for ( ; size2 != 0; size2--) {
              java.lang.CharSequence k2 = null;
              k2 = in.readString(k2 instanceof Utf8 ? (Utf8)k2 : null);
              java.lang.CharSequence v2 = null;
              v2 = in.readString(v2 instanceof Utf8 ? (Utf8)v2 : null);
              m2.put(k2, v2);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










