/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.ccdak.practice.basicKafka.messaging;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ExamFullAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -949011687096356042L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExamFullAvro\",\"namespace\":\"org.ccdak.practice.basicKafka.messaging\",\"fields\":[{\"name\":\"full_message\",\"type\":\"string\"},{\"name\":\"exam\",\"type\":\"ExamFullAvro\",\"doc\":\"Mandatory reference to the external Exam schema\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExamFullAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExamFullAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ExamFullAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ExamFullAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ExamFullAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ExamFullAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ExamFullAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ExamFullAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ExamFullAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence full_message;
  /** Mandatory reference to the external Exam schema */
  private org.ccdak.practice.basicKafka.messaging.ExamFullAvro exam;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExamFullAvro() {}

  /**
   * All-args constructor.
   * @param full_message The new value for full_message
   * @param exam Mandatory reference to the external Exam schema
   */
  public ExamFullAvro(java.lang.CharSequence full_message, org.ccdak.practice.basicKafka.messaging.ExamFullAvro exam) {
    this.full_message = full_message;
    this.exam = exam;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return full_message;
    case 1: return exam;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: full_message = (java.lang.CharSequence)value$; break;
    case 1: exam = (org.ccdak.practice.basicKafka.messaging.ExamFullAvro)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'full_message' field.
   * @return The value of the 'full_message' field.
   */
  public java.lang.CharSequence getFullMessage() {
    return full_message;
  }


  /**
   * Sets the value of the 'full_message' field.
   * @param value the value to set.
   */
  public void setFullMessage(java.lang.CharSequence value) {
    this.full_message = value;
  }

  /**
   * Gets the value of the 'exam' field.
   * @return Mandatory reference to the external Exam schema
   */
  public org.ccdak.practice.basicKafka.messaging.ExamFullAvro getExam() {
    return exam;
  }


  /**
   * Sets the value of the 'exam' field.
   * Mandatory reference to the external Exam schema
   * @param value the value to set.
   */
  public void setExam(org.ccdak.practice.basicKafka.messaging.ExamFullAvro value) {
    this.exam = value;
  }

  /**
   * Creates a new ExamFullAvro RecordBuilder.
   * @return A new ExamFullAvro RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder newBuilder() {
    return new org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder();
  }

  /**
   * Creates a new ExamFullAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExamFullAvro RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder(other);
    }
  }

  /**
   * Creates a new ExamFullAvro RecordBuilder by copying an existing ExamFullAvro instance.
   * @param other The existing instance to copy.
   * @return A new ExamFullAvro RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for ExamFullAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExamFullAvro>
    implements org.apache.avro.data.RecordBuilder<ExamFullAvro> {

    private java.lang.CharSequence full_message;
    /** Mandatory reference to the external Exam schema */
    private org.ccdak.practice.basicKafka.messaging.ExamFullAvro exam;
    private org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder examBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.full_message)) {
        this.full_message = data().deepCopy(fields()[0].schema(), other.full_message);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.exam)) {
        this.exam = data().deepCopy(fields()[1].schema(), other.exam);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasExamBuilder()) {
        this.examBuilder = org.ccdak.practice.basicKafka.messaging.ExamFullAvro.newBuilder(other.getExamBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ExamFullAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.full_message)) {
        this.full_message = data().deepCopy(fields()[0].schema(), other.full_message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exam)) {
        this.exam = data().deepCopy(fields()[1].schema(), other.exam);
        fieldSetFlags()[1] = true;
      }
      this.examBuilder = null;
    }

    /**
      * Gets the value of the 'full_message' field.
      * @return The value.
      */
    public java.lang.CharSequence getFullMessage() {
      return full_message;
    }


    /**
      * Sets the value of the 'full_message' field.
      * @param value The value of 'full_message'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder setFullMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.full_message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'full_message' field has been set.
      * @return True if the 'full_message' field has been set, false otherwise.
      */
    public boolean hasFullMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'full_message' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder clearFullMessage() {
      full_message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'exam' field.
      * Mandatory reference to the external Exam schema
      * @return The value.
      */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro getExam() {
      return exam;
    }


    /**
      * Sets the value of the 'exam' field.
      * Mandatory reference to the external Exam schema
      * @param value The value of 'exam'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder setExam(org.ccdak.practice.basicKafka.messaging.ExamFullAvro value) {
      validate(fields()[1], value);
      this.examBuilder = null;
      this.exam = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'exam' field has been set.
      * Mandatory reference to the external Exam schema
      * @return True if the 'exam' field has been set, false otherwise.
      */
    public boolean hasExam() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'exam' field and creates one if it doesn't exist yet.
     * Mandatory reference to the external Exam schema
     * @return This builder.
     */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder getExamBuilder() {
      if (examBuilder == null) {
        if (hasExam()) {
          setExamBuilder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro.newBuilder(exam));
        } else {
          setExamBuilder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro.newBuilder());
        }
      }
      return examBuilder;
    }

    /**
     * Sets the Builder instance for the 'exam' field
     * Mandatory reference to the external Exam schema
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder setExamBuilder(org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder value) {
      clearExam();
      examBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'exam' field has an active Builder instance
     * Mandatory reference to the external Exam schema
     * @return True if the 'exam' field has an active Builder instance
     */
    public boolean hasExamBuilder() {
      return examBuilder != null;
    }

    /**
      * Clears the value of the 'exam' field.
      * Mandatory reference to the external Exam schema
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.ExamFullAvro.Builder clearExam() {
      exam = null;
      examBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExamFullAvro build() {
      try {
        ExamFullAvro record = new ExamFullAvro();
        record.full_message = fieldSetFlags()[0] ? this.full_message : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (examBuilder != null) {
          try {
            record.exam = this.examBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("exam"));
            throw e;
          }
        } else {
          record.exam = fieldSetFlags()[1] ? this.exam : (org.ccdak.practice.basicKafka.messaging.ExamFullAvro) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExamFullAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExamFullAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExamFullAvro>
    READER$ = (org.apache.avro.io.DatumReader<ExamFullAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.full_message);

    this.exam.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.full_message = in.readString(this.full_message instanceof Utf8 ? (Utf8)this.full_message : null);

      if (this.exam == null) {
        this.exam = new org.ccdak.practice.basicKafka.messaging.ExamFullAvro();
      }
      this.exam.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.full_message = in.readString(this.full_message instanceof Utf8 ? (Utf8)this.full_message : null);
          break;

        case 1:
          if (this.exam == null) {
            this.exam = new org.ccdak.practice.basicKafka.messaging.ExamFullAvro();
          }
          this.exam.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










