/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.ccdak.practice.basicKafka.messaging;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Payload extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8363166665219972226L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Payload\",\"namespace\":\"org.ccdak.practice.basicKafka.messaging\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"test\",\"type\":\"string\"},{\"name\":\"test2\",\"type\":\"string\"},{\"name\":\"test3\",\"type\":\"string\",\"default\":\"false\"},{\"name\":\"test4\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"test5\",\"type\":\"string\",\"default\":\"false\"},{\"name\":\"test6\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Payload> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Payload> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Payload> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Payload> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Payload> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Payload to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Payload from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Payload instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Payload fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence message;
  private java.lang.CharSequence test;
  private java.lang.CharSequence test2;
  private java.lang.CharSequence test3;
  private java.lang.CharSequence test4;
  private java.lang.CharSequence test5;
  private java.lang.CharSequence test6;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Payload() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param test The new value for test
   * @param test2 The new value for test2
   * @param test3 The new value for test3
   * @param test4 The new value for test4
   * @param test5 The new value for test5
   * @param test6 The new value for test6
   */
  public Payload(java.lang.CharSequence message, java.lang.CharSequence test, java.lang.CharSequence test2, java.lang.CharSequence test3, java.lang.CharSequence test4, java.lang.CharSequence test5, java.lang.CharSequence test6) {
    this.message = message;
    this.test = test;
    this.test2 = test2;
    this.test3 = test3;
    this.test4 = test4;
    this.test5 = test5;
    this.test6 = test6;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return test;
    case 2: return test2;
    case 3: return test3;
    case 4: return test4;
    case 5: return test5;
    case 6: return test6;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    case 1: test = (java.lang.CharSequence)value$; break;
    case 2: test2 = (java.lang.CharSequence)value$; break;
    case 3: test3 = (java.lang.CharSequence)value$; break;
    case 4: test4 = (java.lang.CharSequence)value$; break;
    case 5: test5 = (java.lang.CharSequence)value$; break;
    case 6: test6 = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'test' field.
   * @return The value of the 'test' field.
   */
  public java.lang.CharSequence getTest() {
    return test;
  }


  /**
   * Sets the value of the 'test' field.
   * @param value the value to set.
   */
  public void setTest(java.lang.CharSequence value) {
    this.test = value;
  }

  /**
   * Gets the value of the 'test2' field.
   * @return The value of the 'test2' field.
   */
  public java.lang.CharSequence getTest2() {
    return test2;
  }


  /**
   * Sets the value of the 'test2' field.
   * @param value the value to set.
   */
  public void setTest2(java.lang.CharSequence value) {
    this.test2 = value;
  }

  /**
   * Gets the value of the 'test3' field.
   * @return The value of the 'test3' field.
   */
  public java.lang.CharSequence getTest3() {
    return test3;
  }


  /**
   * Sets the value of the 'test3' field.
   * @param value the value to set.
   */
  public void setTest3(java.lang.CharSequence value) {
    this.test3 = value;
  }

  /**
   * Gets the value of the 'test4' field.
   * @return The value of the 'test4' field.
   */
  public java.lang.CharSequence getTest4() {
    return test4;
  }


  /**
   * Sets the value of the 'test4' field.
   * @param value the value to set.
   */
  public void setTest4(java.lang.CharSequence value) {
    this.test4 = value;
  }

  /**
   * Gets the value of the 'test5' field.
   * @return The value of the 'test5' field.
   */
  public java.lang.CharSequence getTest5() {
    return test5;
  }


  /**
   * Sets the value of the 'test5' field.
   * @param value the value to set.
   */
  public void setTest5(java.lang.CharSequence value) {
    this.test5 = value;
  }

  /**
   * Gets the value of the 'test6' field.
   * @return The value of the 'test6' field.
   */
  public java.lang.CharSequence getTest6() {
    return test6;
  }


  /**
   * Sets the value of the 'test6' field.
   * @param value the value to set.
   */
  public void setTest6(java.lang.CharSequence value) {
    this.test6 = value;
  }

  /**
   * Creates a new Payload RecordBuilder.
   * @return A new Payload RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Payload.Builder newBuilder() {
    return new org.ccdak.practice.basicKafka.messaging.Payload.Builder();
  }

  /**
   * Creates a new Payload RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Payload RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Payload.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.Payload.Builder other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.Payload.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.Payload.Builder(other);
    }
  }

  /**
   * Creates a new Payload RecordBuilder by copying an existing Payload instance.
   * @param other The existing instance to copy.
   * @return A new Payload RecordBuilder
   */
  public static org.ccdak.practice.basicKafka.messaging.Payload.Builder newBuilder(org.ccdak.practice.basicKafka.messaging.Payload other) {
    if (other == null) {
      return new org.ccdak.practice.basicKafka.messaging.Payload.Builder();
    } else {
      return new org.ccdak.practice.basicKafka.messaging.Payload.Builder(other);
    }
  }

  /**
   * RecordBuilder for Payload instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Payload>
    implements org.apache.avro.data.RecordBuilder<Payload> {

    private java.lang.CharSequence message;
    private java.lang.CharSequence test;
    private java.lang.CharSequence test2;
    private java.lang.CharSequence test3;
    private java.lang.CharSequence test4;
    private java.lang.CharSequence test5;
    private java.lang.CharSequence test6;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.Payload.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.test)) {
        this.test = data().deepCopy(fields()[1].schema(), other.test);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.test2)) {
        this.test2 = data().deepCopy(fields()[2].schema(), other.test2);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.test3)) {
        this.test3 = data().deepCopy(fields()[3].schema(), other.test3);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.test4)) {
        this.test4 = data().deepCopy(fields()[4].schema(), other.test4);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.test5)) {
        this.test5 = data().deepCopy(fields()[5].schema(), other.test5);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.test6)) {
        this.test6 = data().deepCopy(fields()[6].schema(), other.test6);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Payload instance
     * @param other The existing instance to copy.
     */
    private Builder(org.ccdak.practice.basicKafka.messaging.Payload other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.test)) {
        this.test = data().deepCopy(fields()[1].schema(), other.test);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.test2)) {
        this.test2 = data().deepCopy(fields()[2].schema(), other.test2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.test3)) {
        this.test3 = data().deepCopy(fields()[3].schema(), other.test3);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.test4)) {
        this.test4 = data().deepCopy(fields()[4].schema(), other.test4);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.test5)) {
        this.test5 = data().deepCopy(fields()[5].schema(), other.test5);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.test6)) {
        this.test6 = data().deepCopy(fields()[6].schema(), other.test6);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'test' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest() {
      return test;
    }


    /**
      * Sets the value of the 'test' field.
      * @param value The value of 'test'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.test = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'test' field has been set.
      * @return True if the 'test' field has been set, false otherwise.
      */
    public boolean hasTest() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'test' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest() {
      test = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'test2' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest2() {
      return test2;
    }


    /**
      * Sets the value of the 'test2' field.
      * @param value The value of 'test2'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest2(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.test2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'test2' field has been set.
      * @return True if the 'test2' field has been set, false otherwise.
      */
    public boolean hasTest2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'test2' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest2() {
      test2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'test3' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest3() {
      return test3;
    }


    /**
      * Sets the value of the 'test3' field.
      * @param value The value of 'test3'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest3(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.test3 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'test3' field has been set.
      * @return True if the 'test3' field has been set, false otherwise.
      */
    public boolean hasTest3() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'test3' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest3() {
      test3 = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'test4' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest4() {
      return test4;
    }


    /**
      * Sets the value of the 'test4' field.
      * @param value The value of 'test4'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest4(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.test4 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'test4' field has been set.
      * @return True if the 'test4' field has been set, false otherwise.
      */
    public boolean hasTest4() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'test4' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest4() {
      test4 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'test5' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest5() {
      return test5;
    }


    /**
      * Sets the value of the 'test5' field.
      * @param value The value of 'test5'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest5(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.test5 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'test5' field has been set.
      * @return True if the 'test5' field has been set, false otherwise.
      */
    public boolean hasTest5() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'test5' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest5() {
      test5 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'test6' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest6() {
      return test6;
    }


    /**
      * Sets the value of the 'test6' field.
      * @param value The value of 'test6'.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder setTest6(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.test6 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'test6' field has been set.
      * @return True if the 'test6' field has been set, false otherwise.
      */
    public boolean hasTest6() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'test6' field.
      * @return This builder.
      */
    public org.ccdak.practice.basicKafka.messaging.Payload.Builder clearTest6() {
      test6 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Payload build() {
      try {
        Payload record = new Payload();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.test = fieldSetFlags()[1] ? this.test : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.test2 = fieldSetFlags()[2] ? this.test2 : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.test3 = fieldSetFlags()[3] ? this.test3 : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.test4 = fieldSetFlags()[4] ? this.test4 : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.test5 = fieldSetFlags()[5] ? this.test5 : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.test6 = fieldSetFlags()[6] ? this.test6 : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Payload>
    WRITER$ = (org.apache.avro.io.DatumWriter<Payload>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Payload>
    READER$ = (org.apache.avro.io.DatumReader<Payload>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.message);

    out.writeString(this.test);

    out.writeString(this.test2);

    out.writeString(this.test3);

    out.writeString(this.test4);

    out.writeString(this.test5);

    out.writeString(this.test6);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      this.test = in.readString(this.test instanceof Utf8 ? (Utf8)this.test : null);

      this.test2 = in.readString(this.test2 instanceof Utf8 ? (Utf8)this.test2 : null);

      this.test3 = in.readString(this.test3 instanceof Utf8 ? (Utf8)this.test3 : null);

      this.test4 = in.readString(this.test4 instanceof Utf8 ? (Utf8)this.test4 : null);

      this.test5 = in.readString(this.test5 instanceof Utf8 ? (Utf8)this.test5 : null);

      this.test6 = in.readString(this.test6 instanceof Utf8 ? (Utf8)this.test6 : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 1:
          this.test = in.readString(this.test instanceof Utf8 ? (Utf8)this.test : null);
          break;

        case 2:
          this.test2 = in.readString(this.test2 instanceof Utf8 ? (Utf8)this.test2 : null);
          break;

        case 3:
          this.test3 = in.readString(this.test3 instanceof Utf8 ? (Utf8)this.test3 : null);
          break;

        case 4:
          this.test4 = in.readString(this.test4 instanceof Utf8 ? (Utf8)this.test4 : null);
          break;

        case 5:
          this.test5 = in.readString(this.test5 instanceof Utf8 ? (Utf8)this.test5 : null);
          break;

        case 6:
          this.test6 = in.readString(this.test6 instanceof Utf8 ? (Utf8)this.test6 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










