// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_login.proto

package org.ccdak.practice.basicKafka.messaging;

public final class UserLoginProto {
  private UserLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <pre>
     * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     * Tag 2 is the Timestamp.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.UserLogin.DeviceType device = 3;</code>
     * @return The enum numeric value on the wire for device.
     */
    int getDeviceValue();
    /**
     * <code>.UserLogin.DeviceType device = 3;</code>
     * @return The device.
     */
    org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType getDevice();
  }
  /**
   * <pre>
   * 3. The actual message definition
   * </pre>
   *
   * Protobuf type {@code UserLogin}
   */
  public static final class UserLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserLogin)
      UserLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserLogin.newBuilder() to construct.
    private UserLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserLogin() {
      username_ = "";
      device_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserLogin();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ccdak.practice.basicKafka.messaging.UserLoginProto.internal_static_UserLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ccdak.practice.basicKafka.messaging.UserLoginProto.internal_static_UserLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.class, org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.Builder.class);
    }

    /**
     * <pre>
     * Tag 3 is an Enum (Protobuf handles Enums natively)
     * </pre>
     *
     * Protobuf enum {@code UserLogin.DeviceType}
     */
    public enum DeviceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Proto3 requires a 0 value default
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>MOBILE = 1;</code>
       */
      MOBILE(1),
      /**
       * <code>WEB = 2;</code>
       */
      WEB(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Proto3 requires a 0 value default
       * </pre>
       *
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>MOBILE = 1;</code>
       */
      public static final int MOBILE_VALUE = 1;
      /**
       * <code>WEB = 2;</code>
       */
      public static final int WEB_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DeviceType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DeviceType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return MOBILE;
          case 2: return WEB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DeviceType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
              public DeviceType findValueByNumber(int number) {
                return DeviceType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.getDescriptor().getEnumTypes().get(0);
      }

      private static final DeviceType[] VALUES = values();

      public static DeviceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DeviceType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:UserLogin.DeviceType)
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <pre>
     * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_ = 0L;
    /**
     * <pre>
     * Tag 2 is the Timestamp.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DEVICE_FIELD_NUMBER = 3;
    private int device_ = 0;
    /**
     * <code>.UserLogin.DeviceType device = 3;</code>
     * @return The enum numeric value on the wire for device.
     */
    @java.lang.Override public int getDeviceValue() {
      return device_;
    }
    /**
     * <code>.UserLogin.DeviceType device = 3;</code>
     * @return The device.
     */
    @java.lang.Override public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType getDevice() {
      org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType result = org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.forNumber(device_);
      return result == null ? org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (device_ != org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.UNKNOWN.getNumber()) {
        output.writeEnum(3, device_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (device_ != org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, device_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin)) {
        return super.equals(obj);
      }
      org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin other = (org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (device_ != other.device_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + DEVICE_FIELD_NUMBER;
      hash = (53 * hash) + device_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 3. The actual message definition
     * </pre>
     *
     * Protobuf type {@code UserLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLogin)
        org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ccdak.practice.basicKafka.messaging.UserLoginProto.internal_static_UserLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ccdak.practice.basicKafka.messaging.UserLoginProto.internal_static_UserLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.class, org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.Builder.class);
      }

      // Construct using org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        timestamp_ = 0L;
        device_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ccdak.practice.basicKafka.messaging.UserLoginProto.internal_static_UserLogin_descriptor;
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin getDefaultInstanceForType() {
        return org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.getDefaultInstance();
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin build() {
        org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin buildPartial() {
        org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin result = new org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.device_ = device_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin) {
          return mergeFrom((org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin other) {
        if (other == org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.device_ != 0) {
          setDeviceValue(other.getDeviceValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                device_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <pre>
       * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
       * </pre>
       *
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
       * </pre>
       *
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tag 1 is the ID. Renaming 'username' to 'user_id' later is SAFE.
       * </pre>
       *
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * Tag 2 is the Timestamp.
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * Tag 2 is the Timestamp.
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tag 2 is the Timestamp.
       * </pre>
       *
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int device_ = 0;
      /**
       * <code>.UserLogin.DeviceType device = 3;</code>
       * @return The enum numeric value on the wire for device.
       */
      @java.lang.Override public int getDeviceValue() {
        return device_;
      }
      /**
       * <code>.UserLogin.DeviceType device = 3;</code>
       * @param value The enum numeric value on the wire for device to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceValue(int value) {
        device_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.UserLogin.DeviceType device = 3;</code>
       * @return The device.
       */
      @java.lang.Override
      public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType getDevice() {
        org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType result = org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.forNumber(device_);
        return result == null ? org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType.UNRECOGNIZED : result;
      }
      /**
       * <code>.UserLogin.DeviceType device = 3;</code>
       * @param value The device to set.
       * @return This builder for chaining.
       */
      public Builder setDevice(org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin.DeviceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        device_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.UserLogin.DeviceType device = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        device_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserLogin)
    }

    // @@protoc_insertion_point(class_scope:UserLogin)
    private static final org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin();
    }

    public static org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLogin>
        PARSER = new com.google.protobuf.AbstractParser<UserLogin>() {
      @java.lang.Override
      public UserLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ccdak.practice.basicKafka.messaging.UserLoginProto.UserLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_login.proto\"\207\001\n\tUserLogin\022\020\n\010user" +
      "name\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022%\n\006device\030" +
      "\003 \001(\0162\025.UserLogin.DeviceType\".\n\nDeviceTy" +
      "pe\022\013\n\007UNKNOWN\020\000\022\n\n\006MOBILE\020\001\022\007\n\003WEB\020\002B9\n\'" +
      "org.ccdak.practice.basicKafka.messagingB" +
      "\016UserLoginProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserLogin_descriptor,
        new java.lang.String[] { "Username", "Timestamp", "Device", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
